import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="bg-amber-100 p-4 text-center">
          <h1>Welcome to next js v15</h1>
        </header>
        <main className="bg-slate-50 py-8 px-4">{children}</main>
        <footer className="bg-blue-500 p-4 text-center text-white font-bold capitalize">
          <h1>All rights reserved to the developer</h1>
        </footer>
      </body>
    </html>
  );
}
